apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: fitness-route
spec:
  parentRefs:
  - name: iyas-gateway

  rules:

  # 🔹 FITNESS
  - matches:
    - path:
        type: PathPrefix
        value: /
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: fitness-tracker-service
      port: 80

  # # 🔹 RETAIL
  # - matches:
  #   - path:
  #       type: PathPrefix
  #       value: /retail
  #   filters:
  #   - type: URLRewrite
  #     urlRewrite:
  #       path:
  #         type: ReplacePrefixMatch
  #         replacePrefixMatch: /
  #   backendRefs:
  #   - name: capsule-service
  #     port: 80

  # # 🔹 DEFAULT (hospital)
  # - backendRefs:
  #   - name: hospital-service
  #     port: 80